### ISSUE TITLE
travis isn't useful yet

### ISSUE THREAD

**Issue by CoXier** [zhihu/Matisse#18]
As I see,there isn't any test  in `Matisse` .So why do you use `travis`.

**Comment by unixzii** [comment]
Ah, maybe they just want to keep testing whether it can pass the compilation. LOL

**Comment by CoXier** [comment]
@unixzii 
It seems to make sense.LOL

**Comment by gejiaheng** [comment]
@CoXier @unixzii 
Thanks for reporting this. Actually this is my first time using Travis and I haven't completely set it up. I'll see whether Travis can be somehow useful without any tests. Or I'll turn it off temporarily.

**Comment by unixzii** [comment]
@gejiaheng Yep, Travis CI can be very useful when you want to achieve automation, not only stuff like unit testing, but also releasing.

Let's say you want to publish a test to fir.im whenever you push a commit on specific branch, you can literally write a Gradle script, but instead of doing it on your local machine, Travis can do it for you on its own docker environment, which is pretty handy.

**Comment by gejiaheng** [comment]
@unixzii 
Sounds awesome, thanks for enlightening me!

**Comment by CoXier** [comment]
Now `CheckStyle` is added in travis. [see](https://github.com/zhihu/Matisse/pull/42)
