### ISSUE TITLE
When to use Matisse

### ISSUE THREAD

**Issue by CoXier** [zhihu/Matisse#64]
I guess that `single select` is used for `choosing a photo as user's avatar`. #55 

Up to now,I have not come up with situations where `Matisse` can be used.

As the author @gejiaheng said
> Matisse is a well-designed local image and video selector for Android.

In my life,android app `selector`  has two main usage:
- Choose a photo and crop it as their avatar
- Choose less than or equal 9 photos and then edit chosen photos to upload to moments like `wechat` and `QQ`

It seems `Matisse` can not perform well as needed.However developer can develop their selector based on 
`Matisse`.So I do not think the `gradle import` is necessary because every developer cannt use this lib directly.

**Comment by CoXier** [comment]
#55

**Comment by gejiaheng** [comment]
@CoXier   
As I mentioned in my post [Matisse Android 图片选择器](https://zhuanlan.zhihu.com/p/26420284), the initial intent for us to implement our own media picker is
- Our designer wanted a unified UI & UX on Android and iOS
- We have some special use cases. Like a sequential selecting for product Live.

So from my point of view, if you do have above two needs. You can give Matisse a shot. Or you just want your own media selecting UI instead of system‘s, you can give Matisse a shot.

As for your concerns about those media editing extensions, we can come up a way to implement them. This would be a elegant implementation:
- Matisse core is only for media selecting
- Matisse extensions are for different types of editing
